<?php

/**
 * @package   : 
 *
 * @purpose   :
 * 
 * 
 * @copyright : Copyright (C) 2018-20 H.P.B
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

// module/Album/view/planning/planning/edit.phtml:

$title = 'Edit planning';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$planning = $form->get('TITLE');
$planning->setAttribute('class', 'form-control');
$planning->setAttribute('placeholder', 'Album title');

$artist = $form->get('ARTIST');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('planning', [
    'action' => 'edit',
    'ID'     => $ID,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($planning) ?>
    <?= $this->formElement($planning) ?>
    <?= $this->formElementErrors()->render($planning, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('ID'));
echo $this->form()->closeTag();