<?php  
/**
 * @package   : module/Application/view/partial/breadcrumb.phtml
 *
 * @purpose   :
 * 
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<?php
		// iterate through the pages
		foreach ($this->pages as $key => $page): ?>
			<?php
			// if this isn't the last page, add a link and the separator:
			if ($key < count($this->pages) - 1):
			?>
				<li class="breadcrumb-item">
					<a href="<?= $page->getHref() ?>">
						<?= $page->getLabel() ?>
					</a>
				</li>
			<?php
			// otherwise, output the name only:
			else:
			?>
				<li class="breadcrumb-item active" aria-current="page">
					<?= $page->getLabel() ?>
				</li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ol>
</nav>