<?php
/**
 * @package   : module/Planning/view/planning/anneescolaire/add.phtml
 *
 * @purpose   : Année scolaire add
 * 
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Ajout d'une nouvelle année scolaire";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('Année scolaire');
$this->pageBreadcrumbs()->setItems([
  'Accueil'            => $this->url('home'),
	'Planning Transport' => $this->url('planningtransport'),
	'Année Scolaire'     => $this->url('anneescolaire'),
  'Ajout'              => $this->url('anneescolaire', ['action'=>'add']),
]);

$form->get('ANNEEANNEESCOLAIRE')->setAttributes([
  'class'=>'form-control', 
  'placeholder'=>'Année scolaire'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'fade', 'show', 'alert-danger']);
echo $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-success']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'fade', 'show', 'alert-info']);
?>
<div class="text-center">
  <h2><?= $this->escapeHtml($title) ?></h2>
  <!--
  <p>
    Remplissez la donnée suivante et cliquez sur le bouton <i>Sauver</i>.
  </p>
  -->
</div>
<div class="row justify-content-center">
  <div class="col-md-6 ">
    <?= $this->form()->openTag($form); ?>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('ANNEEANNEESCOLAIRE')); ?>
        <?= $this->formLabel($form->get('ANNEEANNEESCOLAIRE')); ?>
        <?= $this->formElementErrors($form->get('ANNEEANNEESCOLAIRE')); ?>              
      </div>
      <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
      <?php //<?= $this->formElement($form->get('submit')) . PHP_EOL; ?>
      <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
      <?= PHP_EOL; ?>
    <?= $this->form()->closeTag() . PHP_EOL; ?>
  </div>    
</div>