<?php
/**
 * Add a new ephemeride
 * 
 * @package   module/Transport/view/transport/ephemeride/add.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/
$title = "Ajout d'une éphéméride";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'              => $this->url('home'),
  'Transport\Ephéméride' => $this->url($this->module),
  'Ajout'                => $this->url($this->module, ['action'=>'add']),
]);

$form->get('IDX_ANNEESCOLAIRE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Année scolaire'
]);
$form->get('IDX_ANNEESCOLAIRE')->setValueOptions($anneesScolaires);

$form->get('NOMEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Nom éphéméride'
]);

$form->get('STARTDATEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Date début'
]);

$form->get('ENDDATEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Date fin'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true'
]);

$form->prepare();
?>
<div class="container">
  <h2 class="pb-2 border-bottom"><?= $this->escapeHtml($title) ?></h2>
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>   
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        <hr class="my-4">    
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_ANNEESCOLAIRE')) . "\n"; ?>
          <?= $this->formLabel($form->get('IDX_ANNEESCOLAIRE')); ?>
          <?= $this->formElementErrors($form->get('IDX_ANNEESCOLAIRE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('NOMEPHEMERIDE')); ?>
          <?= $this->formLabel($form->get('NOMEPHEMERIDE')); ?>
          <?= $this->formElementErrors($form->get('NOMEPHEMERIDE')); ?>              
        </div>        
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('STARTDATEPHEMERIDE')); ?>
          <?= $this->formLabel($form->get('STARTDATEPHEMERIDE')); ?>
          <?= $this->formElementErrors($form->get('STARTDATEPHEMERIDE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('ENDDATEPHEMERIDE')); ?>
          <?= $this->formLabel($form->get('ENDDATEPHEMERIDE')); ?>
          <?= $this->formElementErrors($form->get('ENDDATEPHEMERIDE')); ?>              
        </div>
        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
        <hr class="my-4"> 
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>