<?php
/**
 * @package   : module/Transport/view/transport/ephemeride/edit.phtml
 *
 * @purpose   : IndisponibiliteChauffeur edit
 * 
 * 
 * @copyright : Copyright (C) 2018-22 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Modification d'une éphéméride";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('ephemeride');
$this->pageBreadcrumbs()->setItems([
  'Accueil'              => $this->url('home'),
  'Transport\Ephéméride' => $this->url('ephemeride'),
  'Modification'         => $this->url('ephemeride', ['action'=>'edit']),
]);

$form->get('IDX_ANNEESCOLAIRE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Chauffeur'
]);
$form->get('IDX_ANNEESCOLAIRE')->setValueOptions($anneesScolaires);

$form->get('NOMEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Nom'
]);

$form->get('STARTDATEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Date début'
]);

$form->get('ENDDATEPHEMERIDE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Date fin'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true'
]);

$form->prepare();
?>

<div class="container">
  <h2 class="pb-2 border-bottom"><?= $this->escapeHtml($title) ?></h2>
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>   
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        
        <hr class="my-4">    
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_ANNEESCOLAIRE')) . "\n"; ?>
          <?= $this->formLabel($form->get('IDX_ANNEESCOLAIRE')); ?>
          <?= $this->formElementErrors($form->get('IDX_ANNEESCOLAIRE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('NOMEPHEMERIDE')); ?>
          <?= $this->formLabel($form->get('NOMEPHEMERIDE')); ?>
          <?= $this->formElementErrors($form->get('NOMEPHEMERIDE')); ?>              
        </div>        
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('STARTDATEINDISPONIBILITE')); ?>
          <?= $this->formLabel($form->get('STARTDATEINDISPONIBILITE')); ?>
          <?= $this->formElementErrors($form->get('STARTDATEINDISPONIBILITE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('ENDDATEINDISPONIBILITE')); ?>
          <?= $this->formLabel($form->get('ENDDATEINDISPONIBILITE')); ?>
          <?= $this->formElementErrors($form->get('ENDDATEINDISPONIBILITE')); ?>              
        </div>

        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>