<?php
/**
 * Display unavailabilities of vehicle
 * 
 * @package   module/Transport/view/transport/indisponibilite-vehicule/index.phtml
 * @version   1.0.1
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Liste des indisponibilités des véhicules';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('indisponibilitevehicule');
$this->pageBreadcrumbs()->setItems([
  'Accueil'                        => $this->url('home'),
  'Transport\Dashboard'            => $this->url('dashboard'),
  'Indisponibilités des véhicules' => $this->url($this->module),
]);

$paginator = $this->paginationControl(
  $this->indisponibilitesVehicules, // Paginator
  'sliding',                         // Style 'all' | 'elastic' | 'sliding' | 'jumping'
  'partial/paginator',               // You can add file extension but helper actually takes care about it  
  [                                  // Parameters 
    'rowPerPage'     => $this->rowPerPage,
    'stepRowPerPage' => $this->stepRowPerPage,
    'search'         => $this->search,
  ]
);

$formSearch->get('search')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Recherche d'une indisponibilité par sa date de début",
]);

$formSearch->setAttribute('action', $this->url($this->module, ['action' => 'index']));

$formSearch->prepare();
?>
<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#arrow_entrance_exit_internet_log_out_security_icon"/></svg>
    <?= $this->escapeHtml($title) ?>
  </h2>
  <div class="row my-4">
    <div class="col-sm" aria-label="add item">
      <a class="btn btn-light btn-outline-primary" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'add']); ?>">
        <span class="far fa-plus-square" aria-hidden="true"></span>
      </a>
    </div>
    <div class="col-sm" aria-label="search item">
      <?= $this->form()->openTag($this->formSearch) . PHP_EOL; ?>
      <div class="row">
        <div class="col">
          <?= $this->formElement($this->formSearch->get('search')) ?>
          <?= $this->formElement($this->formSearch->get('csrf')) . PHP_EOL; ?>
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-light btn-outline-dark"><span class="fas fa-search"></span></button>
          <a class="btn btn-light btn-outline-dark" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'index'], ['query' => ['search' => '']]); ?>">
            <span class="fas fa-recycle" aria-hidden="true"></span>
          </a>
        </div>
      </div>
      <?= $this->form()->closeTag() ?>  
    </div>
  </div>
  <?= $paginator; ?>
  <table class="table align-middle table-striped table-hover table-sm">
    <thead class="table-light">
      <tr>  
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Date début</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Vehicule</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Jour entier</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Heure début</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Date fin</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Heure fin</th>
        <th class="col-sm-2 col-md-2 col-lg-2 col-xl-2">Actions</th>
      </tr>
    </thead>
    <tbody>
  <?php foreach ($this->indisponibilitesVehicules as $indisponibiliteVehicule) : ?>
      <tr>
        <td><?= $this->escapeHtml($indisponibiliteVehicule->getDateDebut()) ?></td>
        <td><?= $this->escapeHtml($indisponibiliteVehicule->getNomVehicule()) ?></td>
        <td>
          <?php 
            $jourEntier = $indisponibiliteVehicule->getJourEntier();
            $checkSVG = ($jourEntier) ? "check_square" : "square";
          ?>
          <svg class="bi text-muted flex-shrink-0 me-3" width="1em" height="1em"><use xlink:href="#<?= $checkSVG ?>"/></svg>
        </td>
        <?php 
          if (!$jourEntier) {
            echo '<td>' . $this->escapeHtml($indisponibiliteVehicule->getHeureDebut()) . '</td>';
            echo '<td>' . $this->escapeHtml($indisponibiliteVehicule->getDateFin()) . '</td>';
            echo '<td>' . $this->escapeHtml($indisponibiliteVehicule->getHeureFin()) . '</td>';
          } else {
            echo '<td>' . '-' . '</td>' ;
            echo '<td>' . '-' . '</td>' ;
            echo '<td>' . '-' . '</td>' ;
          }
        ?>
        <td>
          <a class="btn btn-light btn-outline-warning" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'edit', 'id'=>$indisponibiliteVehicule->getId()]); ?>">
            <span class="far fa-edit" aria-hidden="true"></span>
          </a>
          <a class="btn btn-light btn-outline-danger" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'delete', 'id'=>$indisponibiliteVehicule->getId()]); ?>">
            <span class="far fa-trash-alt"></span>
          </a>
        </td>
      </tr>
  <?php endforeach; ?>
    </tbody>
  </table>
  <?= $paginator; ?>
</div>
<script type="text/javascript">
  function submitformPaginatorNbrPages(value)
  {
    
<?php $query = ($search) ? ['page' => 1, 'search' => $search] : ['page' => 1] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&rowPerPage=" + value ;

    window.location.replace(url);
  }
  
  function submitformPaginatorPages(value)
  {
    
<?php $query = ($search) ? ['search' => $search] : ['search' => ''] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&page=" + value ;;

    window.location.replace(url);
  }
</script>
