<?php
/**
 * Add a new vehicle
 * 
 * @package   module/Transport/view/transport/vehicule/add.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/
 
$title = "Ajout d'un véhicule";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'), 
  'Véhicule'            => $this->url($this->module), 
  'Ajout'               => $this->url($this->module, ['action'=>'add']),
]);

$form->get('NOMVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Nom du véhicule',
]);

$form->get('PLACESVEHICULES')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Places du véhicule'
]);

$form->get('NUMEROVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Numéro du véhicule'
]);

$form->get('PLAQUEVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Plaque du véhicule'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

?>
<div class="text-center">
  <h2><?= $this->escapeHtml($title) ?></h2>
</div>
<div class="row justify-content-center">
  <div class="col-md-6">
    <?= $this->form()->openTag($form); ?>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('NOMVEHICULE')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('NOMVEHICULE')); ?>
        <?= $this->formElementErrors($form->get('NOMVEHICULE')); ?>              
      </div>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('PLACESVEHICULES')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('PLACESVEHICULES')); ?>
        <?= $this->formElementErrors($form->get('PLACESVEHICULES')); ?>              
      </div>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('NUMEROVEHICULE')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('NUMEROVEHICULE')); ?>
        <?= $this->formElementErrors($form->get('NUMEROVEHICULE')); ?>              
      </div>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('PLAQUEVEHICULE')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('PLAQUEVEHICULE')); ?>
        <?= $this->formElementErrors($form->get('PLAQUEVEHICULE')); ?>              
      </div>
      <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
      <?php //<?= $this->formElement($form->get('submit')) . PHP_EOL; ?>
      <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
      <?= PHP_EOL; ?>
    <?= $this->form()->closeTag() . PHP_EOL; ?>
  </div>    
</div>
