<?php
/**
 * Display vehicle
 * 
 * @package   module/Transport/view/transport/vehicule/info.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Informations sur un véhicule';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
  'Véhicule'            => $this->url($this->module), 
  'Info'                => $this->url($this->module, ['action'=>'info']),
]);
?>

<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#school-bus"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>
  
  <div class="row justify-content-left">
    <div class="col-6">
      <table class="table align-middle table-striped table-hover table-borderless">
        <caption><?= $this->escapeHtml($title) ?></caption>
        <tbody>
          <tr>
            <th scope="row" class="justify-content-left">Nom</th>
            <td><?= $this->escapeHtml($vehicule->getNomVehicule()) ?></td>
          </tr>
          <tr>
            <th scope="row">Place</th>
            <td><?= $this->escapeHtml($vehicule->getPlaces()) ?></td>
          </tr>
          <tr>
            <th scope="row">Numéro</th>
            <td><?= $this->escapeHtml($vehicule->getNumero()) ?></td>
          </tr>
          <tr>
            <th scope="row">Plaque</th>
            <td><?= $this->escapeHtml($vehicule->getPlaque()) ?></td>
          </tr>
          <tr>
            <th scope="row">Marque</th>
            <td><?= $this->escapeHtml($vehicule->getNomMarque()) ?></td>
          </tr>
          <tr>
            <th scope="row">Modèle</th>
            <td><?= $this->escapeHtml($vehicule->getModele()) ?></td>
          </tr>
          <tr>
            <th scope="row">Type</th>
            <td><?= $this->escapeHtml($vehicule->getNomTypeVehicule()) ?></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
