<?php
/**
 * Display vehicle
 * 
 * @package   module/Transport/view/transport/vehicule/info.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Informations sur un véhicule';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Véhicules' => $this->url($this->module),  
  'Info'                => $this->url($this->module, ['action'=>'info']),
]);
?>

<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#school-bus"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>

  <table class="table align-middle table-striped table-hover table-sm">
    <thead class="table-light">
      <tr>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Nom</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Place</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Marque</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Modèle</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><?= $this->escapeHtml($vehicule->getNomVehicule()) ?></td>
        <td><?= $this->escapeHtml($vehicule->getPlaces()) ?></td>
        <td><?= $this->escapeHtml($vehicule->getNomMarque()) ?></td>
        <td><?= $this->escapeHtml($vehicule->getModele()) ?></td>
      </tr>
    </tbody>
  </table>
</div>
