<?php
/**
 * @package   : module/Planning/view/planning-bus/transport/excel.phtml
 *
 * @purpose   :
 * 
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Transport::Génération d'un fichier Excel";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('transport');
$this->pageBreadcrumbs()->setItems([
  'Accueil'            => $this->url('home'),
  'Planning Transport' => $this->url('planningtransport'),  
  'Transport'          => $this->url('transport'),
  'Excel'              => $this->url('transport', ['action'=>'excel']),
  ]);

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'fade', 'show', 'alert-danger']);
echo $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-success']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'fade', 'show', 'alert-info']);

$paginator = $this->paginationControl(
  $this->transportsFull,  // Paginator
  'sliding',              // Style 'all' | 'elastic' | 'sliding' | 'jumping'
  'partial/paginator',    // You can add file extension but helper actually takes care about it  
  [                       // Parameters 
    'rowPerPage'     => $this->rowPerPage,
    'stepRowPerPage' => $this->stepRowPerPage,
    'search'         => $this->search,
  ]     
);

$formSearch->get('search')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Recherche d'un transport par date...",
]);

$formSearch->setAttribute('action', $this->url($this->route, ['action' => 'index']));

$formSearch->prepare();
?>
<div class="text-center">
  <h2><?= $this->escapeHtml($title) ?></h2>
</div>
<div class="row my-4">
  <div class="col-sm" aria-label="search item">
    <?= $this->form()->openTag($formSearch) . PHP_EOL; ?>
    <div class="row">
      <div class="col">
        <?= $this->formElement($formSearch->get('search')) ?>
        <?= $this->formElement($formSearch->get('csrf')) . PHP_EOL; ?>
      </div>
      <div class="col-auto">
        <button type="submit" class="btn btn-light btn-outline-dark"><span class="fas fa-search"></span></button>
        <a class="btn btn-light btn-outline-dark" role="button" aria-pressed="true" href="<?= $this->url('planning', ['action'=>'index'], ['query' => ['search' => '']]); ?>">
          <span class="fas fa-recycle" aria-hidden="true"></span>
        </a>
      </div>
    </div>
    <?= $this->form()->closeTag() ?> 
  </div>
</div>

