<?php
/**
 * Add a new 'marque'
 * 
 * @package   module/Transport/view/transport/chauffeur/add.phtml
 * @version   1.0.1
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/
 
$title = "Ajout d'un chauffeur";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('chauffeur');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
  'Chauffeur'           => $this->url($this->module),
  'Ajout'               => $this->url($this->module, ['action'=>'add']),
]);

$form->get('PRENOMCHAUFFEUR')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Prénom'
]);

$form->get('PRINCIPALCHAUFFEUR')->setAttributes([
  'class'       => 'form-check-input',
  'role'        => 'switch',
  'placeholder' => 'Ce chauffeur est principal'
]);
$form->get('PRINCIPALCHAUFFEUR')->setOptions([
  'class'       => 'form-check-label',
]);

$form->get('ACTIFCHAUFFEUR')->setAttributes([
  'class'       => 'form-check-input',
  'role'        => 'switch',
  'placeholder' => 'Ce chauffeur est actif'
]);
$form->get('ACTIFCHAUFFEUR')->setOptions([
  'class'       => 'form-check-label',
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true'
]);

$form->prepare();
?>
<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#blue_car_steering_whell"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>
  
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        <hr class="my-4">  
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('PRENOMCHAUFFEUR')); ?>
          <?= $this->formLabel($form->get('PRENOMCHAUFFEUR')); ?>
          <?= $this->formElementErrors($form->get('PRENOMCHAUFFEUR')); ?>              
        </div>
        <hr class="my-4">
        <div class="form-floating">
          <div class="form-check form-switch">
            <?= $this->formElement($form->get('PRINCIPALCHAUFFEUR')); ?>
            <?= $this->formLabel($form->get('PRINCIPALCHAUFFEUR')); ?>
            <?= $this->formElementErrors($form->get('PRINCIPALCHAUFFEUR')); ?>              
          </div>
        </div>
        <div class="form-floating">
          <div class="form-check form-switch">
            <?= $this->formElement($form->get('ACTIFCHAUFFEUR')); ?>
            <?= $this->formLabel($form->get('ACTIFCHAUFFEUR')); ?>
            <?= $this->formElementErrors($form->get('ACTIFCHAUFFEUR')); ?>     
          </div>            
        </div>
        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
        <hr class="my-4">
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>