<?php
/**
 * @package   : module/Transport/view/transport/chauffeur/index.phtml
 *
 * @purpose   :
 * 
 * 
 * @copyright : Copyright (C) 2018-22 H.P.B
 *
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Liste des chauffeurs';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('chauffeur');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Chauffeur' => $this->url('chauffeur'),
]);

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'fade', 'show', 'alert-danger']);
echo $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-success']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'fade', 'show', 'alert-info']);

?>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="square" viewBox="0 0 16 16">
    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  </symbol> 
  <symbol id="check_square" viewBox="0 0 16 16">
    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
    <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.235.235 0 0 1 .02-.022z"/>
  </symbol> 
</svg>        

<?php
$paginator = $this->paginationControl(
  $this->chauffeurs,      // Paginator
  'sliding',              // Style 'all' | 'elastic' | 'sliding' | 'jumping'
  'partial/paginator',    // You can add file extension but helper actually takes care about it  
  [                       // Parameters 
    'rowPerPage'     => $this->rowPerPage,
    'stepRowPerPage' => $this->stepRowPerPage,
    'search'         => $this->search,
  ]
);

$formSearch->get('search')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Recherche d'un chauffeur par son prénom...",
]);

$formSearch->setAttribute('action', $this->url($this->module, ['action' => 'index']));

$formSearch->prepare();
?>
<div class="container">
  <h2 class="pb-2 border-bottom"><?= $this->escapeHtml($title) ?></h2>
  <div class="row my-4">
    <div class="col-sm" aria-label="add item">
      <a class="btn btn-light btn-outline-primary" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'add']); ?>">
        <span class="far fa-plus-square" aria-hidden="true"></span>
      </a>
    </div>
    <div class="col-sm" aria-label="search item">
      <?= $this->form()->openTag($this->formSearch) . PHP_EOL; ?>
      <div class="row">
        <div class="col">
          <?= $this->formElement($this->formSearch->get('search')) ?>
          <?= $this->formElement($this->formSearch->get('csrf')) . PHP_EOL; ?>
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-light btn-outline-dark"><span class="fas fa-search"></span></button>
          <a class="btn btn-light btn-outline-dark" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'index'], ['query' => ['search' => '']]); ?>">
            <span class="fas fa-recycle" aria-hidden="true"></span>
          </a>
        </div>
      </div>
      <?= $this->form()->closeTag() ?>  
    </div>
  </div>
  <?= $paginator; ?>
  <table class="table align-middle table-striped table-hover table-sm">
    <thead class="table-light">
      <tr>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Prénom</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Principal</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Actif</th>
        <th class="col-sm-2 col-md-2 col-lg-2 col-xl-2">Actions</th>
      </tr>
    </thead>
    <tbody>
  <?php foreach ($this->chauffeurs as $chauffeur) : ?>
      <tr>
        <td><?= $this->escapeHtml($chauffeur->getPrenom()) ?></td>
        <td>
          <?php $checkSVG = ($chauffeur->getPrincipal()) ? "check_square" : "square"; ?>
          <svg class="bi text-muted flex-shrink-0 me-3" width="1em" height="1em"><use xlink:href="#<?= $checkSVG ?>"/></svg>
        </td>
        <td>
          <?php
            $checkSVG = ($chauffeur->getActif()) ? "check_square" : "square";
          ?>
          <svg class="bi text-muted flex-shrink-0 me-3" width="1em" height="1em"><use xlink:href="#<?= $checkSVG ?>"/></svg>
        <td>
          <a class="btn btn-light btn-outline-warning" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'edit', 'id'=>$chauffeur->getId()]); ?>">
            <span class="far fa-edit" aria-hidden="true"></span>
          </a>
          <a class="btn btn-light btn-outline-danger" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'delete', 'id'=>$chauffeur->getId()]); ?>">
            <span class="far fa-trash-alt"></span>
          </a>
        </td>
      </tr>
  <?php endforeach; ?>
    </tbody>
  </table>
  <?= $paginator; ?>
</div>
<script type="text/javascript">
  function submitformPaginatorNbrPages(value)
  {
    
<?php $query = ($search) ? ['page' => 1, 'search' => $search] : ['page' => 1] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&rowPerPage=" + value ;

    window.location.replace(url);
  }
  
  function submitformPaginatorPages(value)
  {
    
<?php $query = ($search) ? ['search' => $search] : ['search' => ''] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&page=" + value ;;

    window.location.replace(url);
  }
</script>
