<?php
/**
 * @package   : module/Transport/view/transport/chauffeur/index.phtml
 *
 * @purpose   :
 * 
 * 
 * @copyright : Copyright (C) 2018-22 H.P.B
 *
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Liste des chauffeurs';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('chauffeur');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Chauffeur' => $this->url('chauffeur'),
]);

$paginator = $this->paginationControl(
  $this->chauffeurs,      // Paginator
  'sliding',              // Style 'all' | 'elastic' | 'sliding' | 'jumping'
  'partial/paginator',    // You can add file extension but helper actually takes care about it  
  [                       // Parameters 
    'rowPerPage'     => $this->rowPerPage,
    'stepRowPerPage' => $this->stepRowPerPage,
    'search'         => $this->search,
  ]
);

$formSearch->get('search')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Recherche d'un chauffeur par son prénom...",
]);

$formSearch->setAttribute('action', $this->url($this->module, ['action' => 'index']));

$formSearch->prepare();
?>
<div class="container">
  <h2 class="pb-2 border-bottom"><?= $this->escapeHtml($title) ?></h2>
  <div class="row my-4">
    <div class="col-sm" aria-label="add item">
      <a class="btn btn-light btn-outline-primary" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'add']); ?>">
        <span class="far fa-plus-square" aria-hidden="true"></span>
      </a>
    </div>
    <div class="col-sm" aria-label="search item">
      <?= $this->form()->openTag($this->formSearch) . PHP_EOL; ?>
      <div class="row">
        <div class="col">
          <?= $this->formElement($this->formSearch->get('search')) ?>
          <?= $this->formElement($this->formSearch->get('csrf')) . PHP_EOL; ?>
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-light btn-outline-dark"><span class="fas fa-search"></span></button>
          <a class="btn btn-light btn-outline-dark" role="button" aria-pressed="true" href="<?= $this->url($this->module, ['action'=>'index'], ['query' => ['search' => '']]); ?>">
            <span class="fas fa-recycle" aria-hidden="true"></span>
          </a>
        </div>
      </div>
      <?= $this->form()->closeTag() ?>  
    </div>
  </div>
  <?= $paginator; ?>
  <table class="table align-middle table-striped table-hover table-sm">
    <thead class="table-light">
      <tr>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Prénom</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Principal</th>
        <th class="col-sm-auto col-md-auto col-lg-auto col-xl-auto">Actif</th>
        <th class="col-sm-2 col-md-2 col-lg-2 col-xl-2">Actions</th>
      </tr>
    </thead>
    <tbody>
  <?php foreach ($this->chauffeurs as $chauffeur) : ?>
      <tr>
        <td><?= $this->escapeHtml($chauffeur->getPrenom()) ?></td>
        <td>
          <?php $checkSVG = ($chauffeur->getPrincipal()) ? "check_square" : "square"; ?>
          <svg class="bi text-muted flex-shrink-0 me-3" width="1em" height="1em"><use xlink:href="#<?= $checkSVG ?>"/></svg>
        </td>
        <td>
          <?php
            $checkSVG = ($chauffeur->getActif()) ? "check_square" : "square";
          ?>
          <svg class="bi text-muted flex-shrink-0 me-3" width="1em" height="1em"><use xlink:href="#<?= $checkSVG ?>"/></svg>
        <td>
          <a class="btn btn-light btn-outline-warning" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'edit', 'id'=>$chauffeur->getId()]); ?>">
            <span class="far fa-edit" aria-hidden="true"></span>
          </a>
          <a class="btn btn-light btn-outline-danger" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'delete', 'id'=>$chauffeur->getId()]); ?>">
            <span class="far fa-trash-alt"></span>
          </a>
        </td>
      </tr>
  <?php endforeach; ?>
    </tbody>
  </table>
  <?= $paginator; ?>
</div>
<script type="text/javascript">
  function submitformPaginatorNbrPages(value)
  {
    
<?php $query = ($search) ? ['page' => 1, 'search' => $search] : ['page' => 1] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&rowPerPage=" + value ;

    window.location.replace(url);
  }
  
  function submitformPaginatorPages(value)
  {
    
<?php $query = ($search) ? ['search' => $search] : ['search' => ''] ?>
    var url = "<?= $this->url($this->route, [], ['query' => $query, 'force_canonical' => true]) ?>" + "&page=" + value ;;

    window.location.replace(url);
  }
</script>
