<?php  
/**
 * @package   : module/Application/view/layout/layout.phtml
 *
 * @purpose   :
 * 
 * 
 * @var       : Laminas\View\Renderer\PhpRenderer $this
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/
?>
<?= $this->doctype() ?>

<html lang="fr">
  <head>
    <meta charset="utf-8">
    <?= $this->headTitle("Cyr's tools")->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Style -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
      ->prependStylesheet($this->basePath('css/style.css'))
      ->prependStylesheet($this->basePath('css/navbar.css'))
      ->prependStylesheet($this->basePath('css/510/bootstrap.min.css'))
      ->prependStylesheet($this->basePath('css/fontawesome/all.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() 
      ->prependFile($this->basePath('js/510/bootstrap.min.js'))
      ->prependFile($this->basePath('js/fontawesome/all.js'))
      ->prependFile($this->basePath('js/jquery-3.6.0.min.js'))
    ?>
    
    <style>
      body, html {
        height: 100%;
        margin: 0;
      }

      .bg {
        background-image: url("<?= $this->basePath('img/bg-tumblr_ls0w5txuft1r3vazto3_400.png') ?>");
        background-repeat: repeat;
        background-attachment: fixed;
      }
    </style>
    
  </head>
  <body class="bg">
    <div class="container">
      <!-- Navigation bar -->
      <div class="row">
        <div class="col-lg-12">
          <?php
          // Check if the activeMenuItemId passed to layout view model
          // and if so, use it for setting active navbar item.
          if (isset($activeMenuItemId)) {
            $this->mainMenu()->setActiveItemId($activeMenuItemId);
          }

          // Render the navbar
          echo $this->mainMenu()->render();
          ?>
        </div>
      </div>
      <!-- Breadcrumbs -->
      <div class="row">
        <div class="col-lg-12">
          <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
      </div>
      <!-- Page content placeholder -->
      <div class="row">
        <div class="col-lg-12">
          <?= $this->content; ?>
        </div>
      </div>
      <hr>
      <footer>
        <div class="text-center">
          <p>&copy; 2018 - <?= date('Y') ?> par <img src="/img/LogoSPFBLo_75x41.png" height="28" width="50" alt="Logo SPFB"> SPFB. Tous droits réservés.</p>
        </div>
      </footer>
    </div>
    <?= $this->inlineScript() ?>
    
  </body>
</html>
