<?php
/**
 * Dashboard of Transport Module 
 *
 * @package   module/Transport/view/transport/dashboard/index.phtml
 * @version   1.0.3
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Tableau de bord du Transport';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url($this->module),
]);
?>

<div class="container" id="dashboard-grid">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#dashboard"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
<!--  
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#cpu-fill"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#home"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#speedometer2"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#toggles2"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#geo-fill"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#tools"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
-->
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#blue_car_steering_whell"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Chauffeurs</h3>
        <p>Gestion des chauffeurs et de leurs indisponibilités</p>
        <p>Nombre de chauffeurs : <?= ($numberOfChauffeur) ? $numberOfChauffeur : '0' ?></p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'index']); ?>" role="button">Chauffeurs</a>
        <a class="btn btn-light btn-outline-danger btn-sm"  role="button" aria-pressed="true" href="<?= $this->url('indisponibilitechauffeur', ['action'=>'index']); ?>" role="button">Indisponibilités</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#day_appointment_schedule_month_event_date_calendar"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">AS &amp; Éphémérides</h3>
        <p>Gestion des années scolaires &amp; de leurs éphémérides</p>
        <p>Il faut créer l'année scolaire avant ses éphémérides</p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('anneescolaire', ['action'=>'index']); ?>" role="button">Années scolaires</a>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('ephemeride', ['action'=>'index']); ?>" role="button">Ephémérides</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#school-bus"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Véhicules</h3>
        <p>Gestion des marques de véhicules, des types de véhicules, des véhicules & de leurs indisponibilités</p>
        <p>Nombre de marques : <?= ($numberOfMarque) ? $numberOfMarque : '0' ?><br />
           Nombre de types : <?= ($numberOfTypeVehicule) ? $numberOfTypeVehicule : '0' ?><br />
           Nombre de véhicules : <?= ($numberOfVehicule) ? $numberOfVehicule : '0' ?></p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('marque', ['action'=>'index']); ?>" role="button">Marques</a>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('typevehicule', ['action'=>'index']); ?>" role="button">Types</a>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('vehicule', ['action'=>'index']); ?>" role="button">Véhicules</a>
        <a class="btn btn-light btn-outline-danger  btn-sm" role="button" aria-pressed="true" href="<?= $this->url('indisponibilitevehicule', ['action'=>'index']); ?>" role="button">Indisponibilités</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#1-15"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Trajets</h3>
        <p>Gestion des trajets</p>
        <p>Il faut créer les étapes d'un trajet avant le trajet</p> 
        <p>Nombre d'étapes : <?= ($numberOfMarque) ? $numberOfEtape : '0' ?><br />
           Nombre de trajets : <?= ($numberOfTrajet) ? $numberOfTrajet : '0' ?></p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('etape', ['action'=>'index']); ?>" role="button">Étapes</a>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('trajet', ['action'=>'index']); ?>" role="button">Trajets</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#account_group_team_user"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Organisation & Groupes</h3>
        <p>Gestion des personnes transportées</p>
        <p>Nombre de groupe : <?= ($numberOfGroupe) ? $numberOfGroupe : '0' ?><br />
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('groupe', ['action'=>'index']); ?>" role="button">Groupes</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#time_Management"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Plannings</h3>
        <p>Gestion des plannings</p>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Plannings</button>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Impression</button>
      </div>
    </div>
  </div>  
</div>
