<?php
/**
 * Dashboard of Transport Module 
 *
 * @package   module/Transport/view/transport/dashboard/index.phtml
 * @version   1.0.1
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = 'Tableau de bord du Transport';
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('dashboard');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
]);
?>

<div class="container" id="dashboard-grid">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#dashboard"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 py-5">
<!--  
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bootstrap"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#cpu-fill"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#home"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#speedometer2"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#toggles2"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#geo-fill"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#tools"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Featured title</h3>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>
-->
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#steering_wheel"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Chauffeurs</h3>
        <p>Gestion des chauffeurs et de leurs indisponibilités</p>
        <p>Nombre de chauffeurs : <?= ($numberOfChauffeur) ? $numberOfChauffeur : '0' ?></p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('chauffeur', ['action'=>'index']); ?>" role="button">Chauffeurs</a>
        <a class="btn btn-light btn-outline-danger btn-sm"  role="button" aria-pressed="true" href="<?= $this->url('indisponibilitechauffeur', ['action'=>'index']); ?>" role="button">Indisponibilités</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">AS &amp; Éphémérides</h3>
        <p>Gestion des années scolaires &amp; de leurs éphémérides</p>
        <p>Il faut créer l'année scolaire avant ses éphémérides</p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('anneescolaire', ['action'=>'index']); ?>" role="button">Années scolaires</a>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('ephemeride', ['action'=>'index']); ?>" role="button">Ephémérides</a>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#truck-front-fill"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Véhicules</h3>
        <p>Gestion des marques de véhicules, des types de véhicules, des véhicules et de leurs indisponibilités</p>
        <p>Nombre de marques : <?= ($numberOfMarque) ? $numberOfMarque : '0' ?><br />
           Nombre de types : <?= ($numberOfTypeVehicule) ? $numberOfTypeVehicule : '0' ?><br />
           Nombre de véhicules : x</p>
        <a class="btn btn-light btn-outline-primary btn-sm" role="button" aria-pressed="true" href="<?= $this->url('marque', ['action'=>'index']); ?>" role="button">Marques</a>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Types</button>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Véhicules</button>
        <button type="button" class="btn btn-outline-danger  btn-sm" disabled>Indisponibilités</button>
      </div>
    </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#signpost-split"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Trajets</h3>
        <p>Gestion des trajets</p>
        <p>Il faut créer les étapes d'un trajet avant le trajet</p> 
        <p>Nombre d'étapes : <?= ($numberOfMarque) ? $numberOfMarque : '0' ?><br />
           Nombre de trajets : <?= ($numberOfTypeVehicule) ? $numberOfTypeVehicule : '0' ?></p>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Etapes</button>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Trajets</button>
      </div>
    </div>
  </div>
    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3-range"/></svg>
      <div>
        <h3 class="fw-bold mb-0 fs-4">Plannings</h3>
        <p>Gestion des plannings</p>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Plannings</button>
        <button type="button" class="btn btn-outline-primary btn-sm" disabled>Impression</button>
      </div>
    </div>
  </div>  
</div>
