<?php
/**
 * Edit a trajet
 * 
 * @package   module/Transport/view/transport/trajet/edit.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/
 
$title = "Modification d'un trajet";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId($this->module);
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
  'Trajet'              => $this->url($this->module), 
  'Modification'        => $this->url($this->module, ['action'=>'edit']),
]);

$form->get('NOMTRAJET')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Nom du trajet",
]);

$form->get('TEMPSTRAJET')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Temps du trajet",
]);

$form->get('KMTRAJET')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Km du trajet'
]);

$form->get('IDX_ETAPEDEPART')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Étape de départ'
]);

$form->get('IDX_ETAPEARRIVEE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Étape d'arrivée"
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

?>
<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#1-15"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>   
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        <hr class="my-4">    
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_ETAPEDEPART')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('IDX_ETAPEDEPART')); ?>
          <?= $this->formElementErrors($form->get('IDX_ETAPEDEPART')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_ETAPEARRIVEE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('IDX_ETAPEARRIVEE')); ?>
          <?= $this->formElementErrors($form->get('IDX_ETAPEARRIVEE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('NOMTRAJET')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('NOMTRAJET')); ?>
          <?= $this->formElementErrors($form->get('NOMTRAJET')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('TEMPSTRAJET')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('TEMPSTRAJET')); ?>
          <?= $this->formElementErrors($form->get('TEMPSTRAJET')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('KMTRAJET')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('KMTRAJET')); ?>
          <?= $this->formElementErrors($form->get('KMTRAJET')); ?>              
        </div>
        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
        <hr class="my-4">
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>
