<?php
/**
 * @package   : module/Planning/view/planning/groupe/add.phtml
 *
 * @purpose   : Groupe add
 * 
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Ajout d'un groupe";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('groupe');
$this->pageBreadcrumbs()->setItems([
  'Accueil'            => $this->url('home'),
  'Planning Transport' => $this->url('planningtransport'),
  'Groupes'            => $this->url('groupe'),
  'Ajout'              => $this->url('groupe', ['action'=>'add']),
]);

$form->get('NOMGROUPE')->setAttributes([
  'class'=>'form-control', 
  'placeholder'=>"Nom de du groupe",
]);

$form->get('NOMBREGROUPE')->setAttributes([
  'class'=>'form-control', 
  'placeholder'=>"Taille du groupe"
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true'
]);

$form->prepare();

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'fade', 'show', 'alert-danger']);
echo $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-success']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'fade', 'show', 'alert-info']);
?>
<div class="text-center">
  <h2><?= $this->escapeHtml($title) ?></h2>
  <!--
  <p>
    Remplissez les données suivantes et cliquez sur le bouton <i>Sauver</i>.
  </p>
  -->
</div>
<div class="row justify-content-center">
  <div class="col-md-6">
    <?= $this->form()->openTag($form) . PHP_EOL; ?>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('NOMGROUPE')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('NOMGROUPE')); ?>
        <?= $this->formElementErrors($form->get('NOMGROUPE')); ?>              
      </div>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('NOMBREGROUPE')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('NOMBREGROUPE')); ?>
        <?= $this->formElementErrors($form->get('NOMBREGROUPE')); ?>              
      </div>
      <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
      <?php //<?= $this->formElement($form->get('submit')) . PHP_EOL; ?>
      <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
      <?= PHP_EOL; ?>
    <?= $this->form()->closeTag() . PHP_EOL; ?>
  </div>    
</div>
