<?php
/**
 * @package   : module/Planning/view/planning/heureplanning/edit.phtml
 *
 * @purpose   : HeurePlanning edit
 * 
 * 
 * @copyright : Copyright (C) 2018-21 H.P.B
 * 
 * @license   : GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Edition d'un heure de planning";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('heureplanning');
$this->pageBreadcrumbs()->setItems([
  'Accueil'            => $this->url('home'),
	'Planning Transport' => $this->url('planningtransport'),
  'Plannings'          => $this->url('planning'),
	'Heures Plannings'   => $this->url('heureplanning'),
  'Edition'            => $this->url('heureplanning', ['action'=>'edit']),
]);

$form->get('HEUREHEUREPLANNING')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Heure du planning",
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

echo $this->flashMessenger()->render('error',   ['alert', 'alert-dismissible', 'fade', 'show', 'alert-danger']);
echo $this->flashMessenger()->render('warning', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-warning']);
echo $this->flashMessenger()->render('success', ['alert', 'alert-dismissible', 'fade', 'show', 'alert-success']);
echo $this->flashMessenger()->render('info',    ['alert', 'alert-dismissible', 'fade', 'show', 'alert-info']);
?>
<div class="text-center">
  <h2><?= $this->escapeHtml($title) ?></h2>
</div>
<div class="row justify-content-center">
  <div class="col-md-6">
    <?= $this->form()->openTag($form) . PHP_EOL; ?>
      <div class="form-floating my-2">
        <?= $this->formElement($form->get('HEUREHEUREPLANNING')) . PHP_EOL; ?>
        <?= $this->formLabel($form->get('HEUREHEUREPLANNING')); ?>
        <?= $this->formElementErrors($form->get('HEUREHEUREPLANNING')); ?>              
      </div>
      <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
      <button heure="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
      <?= PHP_EOL; ?>
    <?= $this->form()->closeTag() . PHP_EOL; ?>
  </div>    
</div>