<?php
/**
 * Edit an étape
 * 
 * @package   module/Transport/view/transport/etape/edit.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Edition d'une étape";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('etape');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
  'Étape'               => $this->url($this->module),
  'Modification'        => $this->url($this->module, ['action'=>'edit']),
]);

$form->get('NOMETAPE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Nom de l'étape",
]);

$form->get('ADRESSEETAPE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => "Adresse de l'étape",
]);

$form->get('PRINTEDETAPE')->setAttributes([
  'class'       => 'form-check-input',
  'role'        => 'switch',
  'placeholder' => 'Étape imprimée ?'
]);
$form->get('PRINTEDETAPE')->setOptions([
  'class'       => 'form-check-label',
]);

$form->get('LATITUDEETAPE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Latitude'
]);

$form->get('LONGITUDEETAPE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Longitude'
]);

$form->get('ALTITUDEETAPE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Altitude'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

?>
<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#location_map_pin_mark"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>   
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        <hr class="my-4">    
       <div class="form-floating my-2">
          <?= $this->formElement($form->get('NOMETAPE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('NOMETAPE')); ?>
          <?= $this->formElementErrors($form->get('NOMETAPE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('ADRESSEETAPE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('ADRESSEETAPE')); ?>
          <?= $this->formElementErrors($form->get('ADRESSEETAPE')); ?>              
        </div>
        <div class="form-floating my-2">
          <div class="form-check form-switch">
            <?= $this->formElement($form->get('PRINTEDETAPE')) . PHP_EOL; ?>
            <?= $this->formLabel($form->get('PRINTEDETAPE')); ?>
            <?= $this->formElementErrors($form->get('PRINTEDETAPE')); ?>     
          </div>           
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('LATITUDEETAPE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('LATITUDEETAPE')); ?>
          <?= $this->formElementErrors($form->get('LATITUDEETAPE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('LONGITUDEETAPE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('LONGITUDEETAPE')); ?>
          <?= $this->formElementErrors($form->get('LONGITUDEETAPE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('ALTITUDEETAPE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('ALTITUDEETAPE')); ?>
          <?= $this->formElementErrors($form->get('ALTITUDEETAPE')); ?>              
        </div>
        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
        <hr class="my-4">
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>