<?php
/**
 * Add a new vehicle
 * 
 * @package   module/Transport/view/transport/vehicule/edit.phtml
 * @version   1.0
 * @copyright 2018-23 H.P.B
 * @author    Marsh <cyril.chable@outlook.be>
 * @license   GNU General Public License version 2 or later; see LICENSE.txt
 **/

$title = "Edition d'un véhicule";
$this->headTitle($title);
$this->mainMenu()->setActiveItemId('vehicule');
$this->pageBreadcrumbs()->setItems([
  'Accueil'             => $this->url('home'),
  'Transport\Dashboard' => $this->url('dashboard'),
  'Véhicule'            => $this->url($this->module),
  'Modification'        => $this->url($this->module, ['action'=>'edit']),
]);

$form->get('IDX_TYPEVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Type de véhicule'
]);
$form->get('IDX_TYPEVEHICULE')->setValueOptions($typeVehicules);

$form->get('IDX_MARQUE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Marque de véhicule'
]);
$form->get('IDX_MARQUE')->setValueOptions($marques);


$form->get('NOMVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Nom du véhicule',
]);

$form->get('PLACESVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Places du véhicule'
]);

$form->get('NUMEROVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Numéro du véhicule'
]);

$form->get('PLAQUEVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Plaque du véhicule'
]);

$form->get('MODELEVEHICULE')->setAttributes([
  'class'       => 'form-control', 
  'placeholder' => 'Modèle du véhicule'
]);

$form->get('submit')->setAttributes([
	'class'        => 'btn btn-outline-warning',
	'role'         => 'button',
	'aria-pressed' => 'true']
	);

$form->prepare();

?>
<div class="container">
  <h2 class="pb-2 border-bottom"><svg class="bi text-muted flex-shrink-0 me-1" width="1em" height="1em"><use xlink:href="#school-bus"/></svg>
  <?= $this->escapeHtml($title) ?>
  </h2>
  <div class="row justify-content-left">
    <div class="col-md-6">
      <?= $this->form()->openTag($form) . PHP_EOL; ?>   
        <button type="submit" class="btn btn-light btn-outline-success"><span class="far fa-save"></span></button>
        <hr class="my-4">    
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_TYPEVEHICULE')) . "\n"; ?>
          <?= $this->formLabel($form->get('IDX_TYPEVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('IDX_TYPEVEHICULE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('IDX_MARQUE')) . "\n"; ?>
          <?= $this->formLabel($form->get('IDX_MARQUE')); ?>
          <?= $this->formElementErrors($form->get('IDX_MARQUE')); ?>              
        </div>
        <hr class="my-4">   
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('NOMVEHICULE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('NOMVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('NOMVEHICULE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('NUMEROVEHICULE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('NUMEROVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('NUMEROVEHICULE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('PLAQUEVEHICULE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('PLAQUEVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('PLAQUEVEHICULE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('PLACESVEHICULE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('PLACESVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('PLACESVEHICULE')); ?>              
        </div>
        <div class="form-floating my-2">
          <?= $this->formElement($form->get('MODELEVEHICULE')) . PHP_EOL; ?>
          <?= $this->formLabel($form->get('MODELEVEHICULE')); ?>
          <?= $this->formElementErrors($form->get('MODELEVEHICULE')); ?>              
        </div>
        <?= $this->formElement($form->get('csrf')) . PHP_EOL; ?>
        <hr class="my-4">
      <?= $this->form()->closeTag() . PHP_EOL; ?>
    </div>    
  </div>
</div>